DELETE FROM CATEGORY;
INSERT INTO CATEGORY(ID,NAME,DESCRIPTION,CODE,PARENT_CATEGORYID,ACTIVE) VALUES (1,'Education','Education','EDU',null,'Y');
INSERT INTO CATEGORY(ID,NAME,DESCRIPTION,CODE,PARENT_CATEGORYID,ACTIVE) VALUES (2,'Entertainment','Entertainment','ENT',null,'Y');
INSERT INTO CATEGORY(ID,NAME,DESCRIPTION,CODE,PARENT_CATEGORYID,ACTIVE) VALUES (3,'Fashion','Fashion','FSH',null,'Y');
INSERT INTO CATEGORY(ID,NAME,DESCRIPTION,CODE,PARENT_CATEGORYID,ACTIVE) VALUES (4,'Health','Health','HLT',null,'Y');
INSERT INTO CATEGORY(ID,NAME,DESCRIPTION,CODE,PARENT_CATEGORYID,ACTIVE) VALUES (5,'Industrial','Industrial','IND',null,'Y');
INSERT INTO CATEGORY(ID,NAME,DESCRIPTION,CODE,PARENT_CATEGORYID,ACTIVE) VALUES (6,'RealEstate','RealEstate','RES',null,'Y');
INSERT INTO CATEGORY(ID,NAME,DESCRIPTION,CODE,PARENT_CATEGORYID,ACTIVE) VALUES (7,'Sports','Sports','SPR',null,'Y');
INSERT INTO CATEGORY(ID,NAME,DESCRIPTION,CODE,PARENT_CATEGORYID,ACTIVE) VALUES (1000,'Miscellaneous','Miscellaneous','MIS',null,'Y');
COMMIT;



