INSERT INTO CATEGORY(ID,NAME,DESCRIPTION,CODE,PARENT_CATEGORYID,ACTIVE) VALUES (1,'Education','Education','EDU',null,'Y');
INSERT INTO CATEGORY(ID,NAME,DESCRIPTION,CODE,PARENT_CATEGORYID,ACTIVE) VALUES (2,'Entertainment','Entertainment','ENT',null,'Y');
INSERT INTO CATEGORY(ID,NAME,DESCRIPTION,CODE,PARENT_CATEGORYID,ACTIVE) VALUES (3,'Fashion','Fashion','FSH',null,'Y');
INSERT INTO CATEGORY(ID,NAME,DESCRIPTION,CODE,PARENT_CATEGORYID,ACTIVE) VALUES (4,'Health','Health','HLT',null,'Y');
INSERT INTO CATEGORY(ID,NAME,DESCRIPTION,CODE,PARENT_CATEGORYID,ACTIVE) VALUES (5,'Industrial','Industrial','IND',null,'Y');
INSERT INTO CATEGORY(ID,NAME,DESCRIPTION,CODE,PARENT_CATEGORYID,ACTIVE) VALUES (6,'RealEstate','RealEstate','RES',null,'Y');
INSERT INTO CATEGORY(ID,NAME,DESCRIPTION,CODE,PARENT_CATEGORYID,ACTIVE) VALUES (7,'Sports','Sports','SPR',null,'Y');


INSERT INTO CATEGORY(ID,NAME,DESCRIPTION,CODE,PARENT_CATEGORYID,ACTIVE) VALUES (10,'Health Education','Health Education','EDU',1,'Y');
INSERT INTO CATEGORY(ID,NAME,DESCRIPTION,CODE,PARENT_CATEGORYID,ACTIVE) VALUES (11,'Technical Education','Technical Education','EDU',1,'Y');
INSERT INTO CATEGORY(ID,NAME,DESCRIPTION,CODE,PARENT_CATEGORYID,ACTIVE) VALUES (12,'Management Education','Management Education','EDU',1,'Y');

INSERT INTO CATEGORY(ID,NAME,DESCRIPTION,CODE,PARENT_CATEGORYID,ACTIVE) VALUES (13,'Auyrvedic','Auyrvedic','EDU',10,'Y');
INSERT INTO CATEGORY(ID,NAME,DESCRIPTION,CODE,PARENT_CATEGORYID,ACTIVE) VALUES (14,'Allopathy','allopathy','EDU',11,'Y');
INSERT INTO CATEGORY(ID,NAME,DESCRIPTION,CODE,PARENT_CATEGORYID,ACTIVE) VALUES (15,'Homeo','Homeo','EDU',12,'Y');

INSERT INTO CATEGORY(ID,NAME,DESCRIPTION,CODE,PARENT_CATEGORYID,ACTIVE) VALUES (16,'Films','Films','ENT',2,'Y');
INSERT INTO CATEGORY(ID,NAME,DESCRIPTION,CODE,PARENT_CATEGORYID,ACTIVE) VALUES (17,'Plays','Plays','ENT',2,'Y');
INSERT INTO CATEGORY(ID,NAME,DESCRIPTION,CODE,PARENT_CATEGORYID,ACTIVE) VALUES (18,'Skits','Skits','ENT',2,'Y');

INSERT INTO CATEGORY(ID,NAME,DESCRIPTION,CODE,PARENT_CATEGORYID,ACTIVE) VALUES (19,'Men','Men','FSH',3,'Y');
INSERT INTO CATEGORY(ID,NAME,DESCRIPTION,CODE,PARENT_CATEGORYID,ACTIVE) VALUES (20,'Women','Women','FSH',3,'Y');

INSERT INTO CATEGORY(ID,NAME,DESCRIPTION,CODE,PARENT_CATEGORYID,ACTIVE) VALUES (21,'Physical','Physical','HLT',4,'Y');
INSERT INTO CATEGORY(ID,NAME,DESCRIPTION,CODE,PARENT_CATEGORYID,ACTIVE) VALUES (22,'Eye','Eye','HLT',4,'Y');


INSERT INTO CATEGORY(ID,NAME,DESCRIPTION,CODE,PARENT_CATEGORYID,ACTIVE) VALUES (23,'Residential','Residential','RES',6,'Y');
INSERT INTO CATEGORY(ID,NAME,DESCRIPTION,CODE,PARENT_CATEGORYID,ACTIVE) VALUES (24,'Commercial','Commercial','RES',6,'Y');

INSERT INTO CATEGORY(ID,NAME,DESCRIPTION,CODE,PARENT_CATEGORYID,ACTIVE) VALUES (25,'Games','Games','SPR',7,'Y');
INSERT INTO CATEGORY(ID,NAME,DESCRIPTION,CODE,PARENT_CATEGORYID,ACTIVE) VALUES (26,'Sports','Games','SPR',7,'Y');

INSERT INTO CATEGORY(ID,NAME,DESCRIPTION,CODE,PARENT_CATEGORYID,ACTIVE) VALUES (27,'Indoor Games','Games','SPR',25,'Y');
INSERT INTO CATEGORY(ID,NAME,DESCRIPTION,CODE,PARENT_CATEGORYID,ACTIVE) VALUES (28,'Outdoor Games','Games','SPR',25,'Y');

INSERT INTO CATEGORY(ID,NAME,DESCRIPTION,CODE,PARENT_CATEGORYID,ACTIVE) VALUES (29,'Carroms','Games','SPR',27,'Y');
INSERT INTO CATEGORY(ID,NAME,DESCRIPTION,CODE,PARENT_CATEGORYID,ACTIVE) VALUES (30,'Shuttle','Games','SPR',28,'Y');


