DROP TABLE IF EXISTS EVENT ;
CREATE TABLE `EVENT` (
   ID bigint(20) NOT NULL AUTO_INCREMENT,
   TITLE varchar(256) NOT NULL,
   DESCRIPTION text,
   PAY_TYPE int(10) NOT NULL,
   START_DATE timestamp NOT NULL,
   END_DATE timestamp NOT NULL,
   SUBCATEGORY_ID bigint(20) NOT NULL,
   ORGANIZER_NAME varchar(128) NOT NULL,
   ORGANIZER_DESC varchar(1000) NULL,
   contact_details varchar(1000) NULL,
   VENUE_NAME varchar(256) NOT NULL,
   VENUE_ADDRESS_ID bigint(20)  NOT NULL,
   ATTEND_TYPE int(2) NULL,
   OCCURING_TYPE int(3) NULL,
   TERMS_CONDITIONS text,
   CREATED_USER_ID bigint(20) NOT NULL,
   ACTIVE char(1) NULL,
   STATUS char(4) NULL,
  PRIMARY KEY (ID)
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=latin1;

DROP TABLE IF EXISTS `EVENT_MEDIA`;
CREATE TABLE `EVENT_MEDIA` (
   EVENT_ID bigint(20) NOT NULL ,
   IMAGE_URL varchar(256) DEFAULT NULL,
   company_logo_url varchar(256),
   VIDEO_URL varchar(256) DEFAULT NULL,
   BANNER_URL varchar(256) NOT NULL,
   FACEBOOK_URL varchar(256) NOT NULL,
   OTHER_URL1 varchar(256) NOT NULL,
   OTHER_URL2 varchar(256) NOT NULL,
  PRIMARY KEY (EVENTID)
) ENGINE=InnoDB  DEFAULT CHARSET=latin1;

DROP TABLE IF EXISTS ADDRESS;
CREATE TABLE ADDRESS (
   ID bigint(20) NOT NULL AUTO_INCREMENT,
   ADDR_LINE1 varchar(256) DEFAULT NULL,
   ADDR_LINE2 varchar(256) DEFAULT NULL,
   CITY_ID bigint(20) NOT NULL,
   ZIP varchar(7) NOT NULL,
   FAX varchar(10) NULL,
   MAP_URL varchar(256) NULL,
   PRIMARY KEY (ID)
) ENGINE=InnoDB  DEFAULT CHARSET=latin1;

DROP TABLE IF EXISTS EVENT_TICKET;
CREATE TABLE EVENT_TICKET(
  ID bigint(20) NOT NULL AUTO_INCREMENT,
  EVENT_ID bigint(20) NOT NULL,
  NAME varchar(128) NOT NULL,
  DESCRIPTION TINYTEXT  NULL,
  SALE_STARTDATE timestamp NOT NULL,
  SALE_ENDDATE timestamp NOT NULL,
  PRICE decimal(10,2) NOT NULL,
  QUANTITY int(10) NOT NULL,
  MIN_QTY int(10) NOT NULL,
  MAX_QTY int(10) NOT NULL,
  ACTIVE char(1) NULL,
  PRIMARY KEY (ID)
);

DROP TABLE IF EXISTS CATEGORY;
CREATE TABLE CATEGORY(
 ID  bigint(20) NOT NULL AUTO_INCREMENT,
 NAME varchar(128) NOT NULL,
 DESCRIPTION varchar(256) NULL,
 CODE varchar(10) NULL,
 PARENT_CATEGORYID bigint(20) NULL,
 ACTIVE char(1) NOT NULL DEFAULT 'Y',
 PRIMARY KEY(ID)
);

DROP TABLE IF EXISTS ORDER;
CREATE TABLE ORDER(
 ID bigint(20) NOT NULL AUTO_INCREMENT,
 BUYER_FNAME varchar(128) NOT NULL,
 BUYER_LNAME varchar(128) NULL,
 BUYER_EMAIL varchar(255) NOT NULL,
 ADDR_ID bigint(20) NOT NULL,

 gross_amount DECIMAL(10,2) NULL,
 netAmount DECIMAL(10,2) NULL,
 discountAmount DECIMAL(10,2) NULL,
 dicountCoupon varchar(20) NULL,
 payment_currency varchar(5) NOT NULL,

 PRIMARY KEY(ID)
);


DROP TABLE IF EXISTS SUBORDER;
CREATE TABLE SUBORDER(
 ID bigint(20) NOT NULL AUTO_INCREMENT,
 TICKET_ID bigint(20) NOT NULL,
 QUANTITY int(5) NOT NULL,
 ORDER_ID bigint(20) NOT NULL,
 SUB_CATEGORYID bigint(20) NOT NULL,
 TICKET_PRICE decimal(10,2) NOT NULL,
 
 gross_amount DECIMAL(10,2) NULL,
 netAmount DECIMAL(10,2) NULL,
 discountAmount DECIMAL(10,2) NULL,
 dicountCoupon varchar(20) NULL,

 STATUS char(5) NULL,
 organizer_name varchar(128) NULL,

  PRIMARY KEY(ID)
);


DROP TABLE IF EXISTS REGISTRATION;
CREATE TABLE REGISTRATION(
 ID bigint(20) NOT NULL AUTO_INCREMENT,
 SUBORDER_ID bigint(20) NOT NULL,
 NAME varchar(256) NOT NULL,
 EMAIL varchar(256) NOT NULL,
 COMPANY varchar(128) NULL,
 PHONE varchar(12) NULL,
 PRIMARY KEY(ID)
);
