DROP TABLE IF EXISTS EVENT ;
CREATE TABLE `EVENT` (
  `EVENTID` bigint(20) NOT NULL AUTO_INCREMENT,
  `EVENTNAME` varchar(256) DEFAULT NULL,
  `EVENTTITLE` varchar(256) NOT NULL,
  `EVENTDESCRIPTION` text,
   EVENTTYPE int(10) NOT NULL,
  `STARTDATE` timestamp NOT NULL,
  `ENDDATE` timestamp NOT NULL,
   PRICE decimal(10,2) NOT NULL,
   CATEGORYID bigint(20),
   SUBCATEGORYID bigint(20) NOT NULL,
   ORGANIZERNAME varchar(128) NOT NULL,
   ORGANIZERADDRID bigint(20) NULL,
   VENUENAME varchar(256) NOT NULL,
   VENUEADDRESSID bigint(20)  NOT NULL,
   EVENTATTENDTYPE int(2) NULL,
   EVENTOCCURINGTYPE int(3) NULL,
   EVENTCONTACT int(10) NULL,
   TERMSANDCONDITIONS text,
   TOTAL_SEATS int(10) NOT NULL,
  PRIMARY KEY (`EVENTID`)
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=latin1;

DROP TABLE IF EXISTS `EVENT_MEDIA`;
CREATE TABLE `EVENT_MEDIA` (
  `EVENTID` bigint(20) NOT NULL ,
  `IMAGE_URL` varchar(256) DEFAULT NULL,
   `VIDEO_URL` varchar(256) DEFAULT NULL,
  `BANNER` varchar(256) NOT NULL,
  `FACEBOOK_URL` varchar(256) NOT NULL,
   `OTHER_URL1` varchar(256) NOT NULL,
   `OTHER_URL2` varchar(256) NOT NULL,
  PRIMARY KEY (`EVENTID`)
) ENGINE=InnoDB  DEFAULT CHARSET=latin1;

DROP TABLE IF EXISTS ADDRESS;
CREATE TABLE ADDRESS (
   ADDID bigint(20) NOT NULL AUTO_INCREMENT,
   ADDR_LINE1 varchar(256) DEFAULT NULL,
   ADDR_LINE2 varchar(256) DEFAULT NULL,
   CITY varchar(256) NOT NULL,
   STATE varchar(256) NOT NULL,
  COUNTRYID bigint(10) NOT NULL,
   ZIP varchar(7) NOT NULL,
   FAX varchar(10) NULL,
  PRIMARY KEY (`ADDID`)
) ENGINE=InnoDB  DEFAULT CHARSET=latin1;

DROP TABLE IF EXISTS EVENT_TICKET;
CREATE TABLE EVENT_TICKET(
  EVENT_TICKET_ID bigint(20) NOT NULL AUTO_INCREMENT,
  EVENT_ID bigint(20) NOT NULL,
  TICKETNAME varchar(128) NOT NULL,
  TICKETDESC TINYTEXT  NULL,
  SALE_STARTDATE timestamp NOT NULL,
  SALE_ENDDATE timestamp NOT NULL,
  PRICE decimal(10,2) NOT NULL,
  MIN_SEATS int(10) NOT NULL,
  MAX_SEATS int(10) NOT NULL,
  ACTIVE char(1) NULL,
  PRIMARY KEY (EVENT_TICKET_ID)
);

DROP TABLE IF EXISTS CATEGORY;
CREATE TABLE CATEGORY(
CATEGORYID bigint(20) NOT NULL AUTO_INCREMENT,
CATEGORY_NAME varchar(128) NOT NULL,
CODE varchar(10) NULL,
PARENT_CATEGORYID bigint(20) NULL,
ACTIVE char(1) NOT NULL DEFAULT 'Y',
PRIMARY KEY(CATEGORYID)
);